siteTitle="Builder"
#baseColor = "#884499"
baseColor = "#cc0000"
linkPrefix = "/builder-site"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
]
